baseURL = 'https://example.org/'
languageCode = 'en-gb'
title = 'Documentation for LidlFysh-IaC'

# hugo module configuration

[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/google/docsy -> ../../docsy"
  [module.hugoVersion]
    extended = true
    min = "0.120.3"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
